/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author Snowgal
 */
public class AlterarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form AlterarPaciente
     */
    public AlterarPaciente() {
        initComponents();
        setSize(800, 600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtRg = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Alterar/Excluir Cadastros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(293, 36, 201, 33);
        getContentPane().add(txtCpf);
        txtCpf.setBounds(230, 100, 326, 34);
        getContentPane().add(txtNome);
        txtNome.setBounds(230, 150, 326, 34);
        getContentPane().add(txtRg);
        txtRg.setBounds(230, 200, 326, 34);
        getContentPane().add(txtData);
        txtData.setBounds(230, 250, 326, 34);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(230, 500, 326, 34);

        btnBuscar.setText("BUSCAR");
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(580, 110, 100, 23);

        jLabel7.setText("CPF:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 110, 70, 14);

        jLabel8.setText("Nome:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 160, 70, 14);

        jLabel9.setText("Nome:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 160, 31, 14);

        jLabel10.setText("Data de Nascimento:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(120, 260, 110, 14);

        jLabel11.setText("Numero:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(120, 360, 70, 14);

        jLabel12.setText("Bairro:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(120, 410, 70, 14);

        jLabel13.setText("CEP:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(120, 460, 70, 14);

        jLabel14.setText("Cidade:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(120, 510, 70, 14);

        jLabel15.setText("Rua:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(120, 310, 70, 14);

        jLabel16.setText("RG:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(120, 210, 70, 14);
        getContentPane().add(txtRua);
        txtRua.setBounds(230, 300, 326, 34);
        getContentPane().add(txtNumero);
        txtNumero.setBounds(230, 350, 326, 34);
        getContentPane().add(txtBairro);
        txtBairro.setBounds(230, 400, 326, 34);
        getContentPane().add(txtCep);
        txtCep.setBounds(230, 450, 326, 34);

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(580, 210, 100, 23);

        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(580, 170, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
