/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import classes.DadoInvalidoException;
import classes.Dentista;
import classes.Endereco;
import classes.Funcionario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.dao.DentistaDAO;

/**
 *
 * @author Ewerton
 */
public class AlterarDentista extends javax.swing.JFrame {

    /**
     * Creates new form AlterarDentista
     */
    Dentista d = new Dentista();
    DentistaDAO ddao = new DentistaDAO();

    public AlterarDentista() {
        initComponents();
        setSize(800, 600);
        setLocationRelativeTo(null);
    }

    public void alterar() throws DadoInvalidoException {
        int g = 0;
        if (txtCPF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite um cpf válido");
        } else {
            txtNome.enable();
            txtCro.enable();
            txtEspecialidade.enable();
            txtFuncao.enable();
            txtRg.enable();
            txtSalario.enable();
            txtRua.enable();
            txtBairro.enable();
            txtCEP.enable();
            txtCidade.enable();
            txtNumero.enable();

            for (Dentista d : ddao.read()) {

                if (d.getCpf().equals(txtCPF.getText())) {

                    double a = d.getSalario();
                    String b;
                    b = String.valueOf(a);

                    txtNome.setText(d.getNome());
                    txtCro.setText(d.getCro());
                    txtEspecialidade.setText(d.getEspecialidade());
                    txtRg.setText(d.getRg());
                    txtSalario.setText(b);
                    txtFuncao.setText(d.getFuncao());

                    txtRua.setText(d.getEndereco().getRua());
                    txtNumero.setText(d.getEndereco().getNumero());
                    txtBairro.setText(d.getEndereco().getBairro());
                    txtCEP.setText(d.getEndereco().getCep());
                    txtCidade.setText(d.getEndereco().getCidade());
                    g = 1;
                    break;
                }
            }
            if (g != 1) {
                JOptionPane.showMessageDialog(null, "Registro não encontrado");
                txtNome.enable(false);
                txtCro.enable(false);
                txtEspecialidade.enable(false);
                txtFuncao.enable(false);
                txtRg.enable(false);;
                txtSalario.enable(false);
                txtRua.enable(false);
                txtBairro.enable(false);
                txtCEP.enable(false);
                txtCidade.enable(false);
                txtNumero.enable(false);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCPF = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtRg = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtEspecialidade = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtFuncao = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        txtCro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCEP = new javax.swing.JTextField();
        btnExluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar/Excluir Dentista");
        getContentPane().setLayout(null);
        getContentPane().add(txtCPF);
        txtCPF.setBounds(110, 100, 510, 34);

        txtNome.setEnabled(false);
        getContentPane().add(txtNome);
        txtNome.setBounds(110, 150, 510, 34);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alterar/Excluir Cadastros de Dentistas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 40, 520, 33);

        txtRg.setEnabled(false);
        getContentPane().add(txtRg);
        txtRg.setBounds(380, 270, 240, 34);

        txtCidade.setEnabled(false);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(300, 490, 320, 34);

        txtEspecialidade.setEnabled(false);
        getContentPane().add(txtEspecialidade);
        txtEspecialidade.setBounds(410, 210, 210, 34);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menor.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(640, 100, 110, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Função:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(10, 280, 70, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CPF:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 120, 70, 15);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Especialidade:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(320, 220, 90, 15);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back.png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 510, 90, 30);

        txtFuncao.setEnabled(false);
        txtFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtFuncao);
        txtFuncao.setBounds(110, 270, 200, 34);

        txtSalario.setEnabled(false);
        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtSalario);
        txtSalario.setBounds(110, 330, 200, 34);

        txtCro.setEnabled(false);
        txtCro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCroActionPerformed(evt);
            }
        });
        getContentPane().add(txtCro);
        txtCro.setBounds(110, 210, 200, 34);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CRO:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 220, 70, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nome:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 170, 60, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Salário:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 340, 90, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Numero:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(490, 400, 70, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bairro:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 450, 70, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CEP:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 500, 70, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cidade:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(240, 500, 60, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Rua:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 400, 70, 15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("RG:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(340, 280, 150, 15);

        txtRua.setEnabled(false);
        getContentPane().add(txtRua);
        txtRua.setBounds(110, 390, 350, 34);

        txtNumero.setEnabled(false);
        getContentPane().add(txtNumero);
        txtNumero.setBounds(550, 390, 70, 34);

        txtBairro.setEnabled(false);
        getContentPane().add(txtBairro);
        txtBairro.setBounds(110, 440, 510, 34);

        txtCEP.setEnabled(false);
        getContentPane().add(txtCEP);
        txtCEP.setBounds(110, 490, 110, 34);

        btnExluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        btnExluir.setText("EXCLUIR");
        btnExluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExluir);
        btnExluir.setBounds(640, 220, 110, 30);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/update.png"))); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(640, 180, 110, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Untitled-1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 600);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nome:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 170, 70, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExluirActionPerformed
         if(txtCPF.getText().isEmpty() || txtCPF.getText()==null){
            JOptionPane.showMessageDialog(null, "Digite um Cpf válido", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                d.setCpf(txtCPF.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
            try {
                int op =JOptionPane.showConfirmDialog(null, "Deseja Realmente excluir o registro " + txtCPF.getText() + "?" , "Aviso", JOptionPane.WARNING_MESSAGE);
                if (op ==0)
                    ddao.delete(d);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        
        
        
    }//GEN-LAST:event_btnExluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (txtNome.getText().isEmpty() || txtNome.getText() == null
                || txtCro.getText().isEmpty() || txtCro.getText() == null
                || txtEspecialidade.getText().isEmpty() || txtEspecialidade.getText() == null
                || txtFuncao.getText().isEmpty() || txtFuncao.getText() == null
                || txtRg.getText().isEmpty() || txtRg.getText() == null
                || txtSalario.getText().isEmpty() || txtSalario.getText() == null
                || txtRua.getText().isEmpty() || txtRua.getText() == null
                || txtNumero.getText().isEmpty() || txtNumero.getText() == null
                || txtBairro.getText().isEmpty() || txtBairro.getText() == null
                || txtCEP.getText().isEmpty() || txtCEP.getText() == null
                || txtCidade.getText().isEmpty() || txtCidade.getText() == null) {

            JOptionPane.showMessageDialog(null, "Algum campo está vazio");
        } else {
            try {
                d.setNome(txtNome.getText());
                d.setCro(txtCro.getText());
                d.setEspecialidade(txtEspecialidade.getText());
                d.setFuncao(txtFuncao.getText());
                d.setRg(txtRg.getText());
                d.setSalario(Double.parseDouble(txtSalario.getText()));
                d.setEndereco(new Endereco());
                d.getEndereco().setRua(txtRua.getText());;
                d.getEndereco().setNumero(txtNumero.getText());
                d.getEndereco().setBairro(txtBairro.getText());
                d.getEndereco().setCep(txtCEP.getText());
                d.getEndereco().setCidade(txtCidade.getText());

                d.setCpf(txtCPF.getText());
            } catch (DadoInvalidoException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        try {
            ddao.update(d);

            txtNome.setText("");
            txtCro.setText("");
            txtEspecialidade.setText("");
            txtFuncao.setText("");
            txtRg.setText("");
            txtSalario.setText("");
            txtCPF.setText("");
            txtRua.setText("");
            txtNumero.setText("");
            txtBairro.setText("");
            txtCEP.setText("");
            txtCidade.setText("");

            txtNome.enable(false);
            txtCro.enable(false);
            txtEspecialidade.enable(false);
            txtFuncao.enable(false);
            txtRg.enable(false);;
            txtSalario.enable(false);
            txtRua.enable(false);
            txtBairro.enable(false);
            txtCEP.enable(false);
            txtCidade.enable(false);
            txtNumero.enable(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            alterar();
        } catch (DadoInvalidoException ex) {
            Logger.getLogger(AlterarDentista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCroActionPerformed

    private void txtFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncaoActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCro;
    private javax.swing.JTextField txtEspecialidade;
    private javax.swing.JTextField txtFuncao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
