/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author Snowgal
 */
public class AlterarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form AlterarPaciente
     */
    public AlterarPaciente() {
        initComponents();
        setSize(800, 600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Alterar/Excluir Cadastros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(293, 36, 201, 33);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 100, 326, 34);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(230, 150, 326, 34);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(230, 200, 326, 34);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(230, 250, 326, 34);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(230, 500, 326, 34);

        jButton1.setText("BUSCAR");
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 110, 100, 23);

        jLabel7.setText("CPF:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 110, 70, 14);

        jLabel8.setText("Nome:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 160, 70, 14);

        jLabel9.setText("Nome:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 160, 31, 14);

        jLabel10.setText("Data de Nascimento:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(120, 260, 110, 14);

        jLabel11.setText("Numero:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(120, 360, 70, 14);

        jLabel12.setText("Bairro:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(120, 410, 70, 14);

        jLabel13.setText("CEP:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(120, 460, 70, 14);

        jLabel14.setText("Cidade:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(120, 510, 70, 14);

        jLabel15.setText("Rua:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(120, 310, 70, 14);

        jLabel16.setText("RG:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(120, 210, 70, 14);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(230, 300, 326, 34);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(230, 350, 326, 34);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(230, 400, 326, 34);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(230, 450, 326, 34);

        jButton2.setText("EXCLUIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 210, 100, 23);

        jButton3.setText("ALTERAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(580, 170, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
