/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author Vanessa Macena
 */
public class CadastroDentista extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroDentista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfCodDentista = new javax.swing.JTextField();
        tfCpfDentista = new javax.swing.JTextField();
        tfRgDentista = new javax.swing.JTextField();
        tfNomeDentista = new javax.swing.JTextField();
        tfFuncaoDentista = new javax.swing.JTextField();
        jbOkFuncionario = new javax.swing.JButton();
        btCancelarFuncionario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfCroDentista = new javax.swing.JTextField();
        tfEspecialidadeDentista = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfSalarioDentista = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones_funcionarios.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(26, 11, 100, 111);

        jLabel2.setText("Cadastro de Dentista");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(136, 91, 140, 14);

        jLabel3.setText("Codigo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 140, 40, 30);

        jLabel4.setText("CPF");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 140, 30, 30);

        jLabel5.setText("RG");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 190, 30, 30);

        jLabel6.setText("Nome");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 140, 40, 30);

        jLabel7.setText("Salário");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(540, 190, 50, 30);

        jLabel9.setText("Função");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(240, 190, 50, 30);
        jPanel1.add(tfCodDentista);
        tfCodDentista.setBounds(60, 140, 40, 30);
        jPanel1.add(tfCpfDentista);
        tfCpfDentista.setBounds(550, 140, 150, 30);
        jPanel1.add(tfRgDentista);
        tfRgDentista.setBounds(70, 190, 150, 30);
        jPanel1.add(tfNomeDentista);
        tfNomeDentista.setBounds(160, 140, 350, 30);
        jPanel1.add(tfFuncaoDentista);
        tfFuncaoDentista.setBounds(320, 190, 160, 30);

        jbOkFuncionario.setText("Ok");
        jPanel1.add(jbOkFuncionario);
        jbOkFuncionario.setBounds(270, 350, 80, 30);

        btCancelarFuncionario.setText("Cancelar");
        jPanel1.add(btCancelarFuncionario);
        btCancelarFuncionario.setBounds(370, 350, 80, 30);

        jButton1.setText("Endereço");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 290, 90, 30);

        jLabel8.setText("CRO");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 250, 30, 14);
        jPanel1.add(tfCroDentista);
        tfCroDentista.setBounds(70, 240, 150, 30);
        jPanel1.add(tfEspecialidadeDentista);
        tfEspecialidadeDentista.setBounds(330, 240, 150, 30);

        jLabel10.setText("Especialidade");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(240, 250, 80, 14);
        jPanel1.add(tfSalarioDentista);
        tfSalarioDentista.setBounds(610, 190, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EndereçoFuncionario ef = new EndereçoFuncionario();
        ef.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarFuncionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbOkFuncionario;
    private javax.swing.JTextField tfCodDentista;
    private javax.swing.JTextField tfCpfDentista;
    private javax.swing.JTextField tfCroDentista;
    private javax.swing.JTextField tfEspecialidadeDentista;
    private javax.swing.JTextField tfFuncaoDentista;
    private javax.swing.JTextField tfNomeDentista;
    private javax.swing.JTextField tfRgDentista;
    private javax.swing.JTextField tfSalarioDentista;
    // End of variables declaration//GEN-END:variables
}
