/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import bancodedados.Conectar;
import classes.DespesaGanho;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.dao.DespesaGanhoDAO;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Bruno Cavalcante
 */
public class FormFluxoCaixa extends javax.swing.JFrame {

    /**
     * Creates new form FluxoCaixa
     */
    Connection conecta;
    PreparedStatement pst;
    ResultSet rs;

    public FormFluxoCaixa() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(820, 647);
        conecta = Conectar.getConnection();
        readFluxo();
       // totalDespesa();
    }

    public void readFluxo() {
        String sql = "select * from despesaganho";
        try {
            pst = conecta.prepareStatement(sql);
            rs = pst.executeQuery();
            jTableFluxo.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, erro);
        }

    }

//    public void totalDespesa() {
//        Connection con = Conectar.getConnection();
//        PreparedStatement stmt = null;
//        double total = 0;
//        try {
//            ResultSet rs = stmt
//                    .executeQuery("SELECT sum(valor)AS total FROM despesaganho");
//            while (rs.next()) {
//                total = rs.getDouble("total");
//            }
//        } catch (SQLException e) {
//        }
//        txtTotal.setText("" + total);
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tfDescrição = new javax.swing.JTextField();
        tfValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFluxo = new javax.swing.JTable();
        btnInserir = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fluxo de Caixa");
        setPreferredSize(new java.awt.Dimension(988, 526));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 300));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fluxo-de-caixa3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(11, 12, 131, 98);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Fluxo de caixa");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(148, 74, 98, 16);

        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Ganho / Despesa:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(19, 137, 103, 27);

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Ganho", "Despesa" }));
        jPanel1.add(jComboBox);
        jComboBox.setBounds(20, 160, 110, 30);

        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Data:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 220, 50, 20);
        jPanel1.add(tfDescrição);
        tfDescrição.setBounds(148, 160, 411, 30);
        jPanel1.add(tfValor);
        tfValor.setBounds(600, 160, 59, 30);

        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Valor:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(600, 140, 35, 14);

        jTableFluxo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableFluxo);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(140, 260, 651, 310);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        jPanel1.add(btnInserir);
        btnInserir.setBounds(680, 160, 73, 30);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(200, 210, 91, 30);

        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Descrição:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(148, 140, 65, 20);
        jPanel1.add(txtTotal);
        txtTotal.setBounds(610, 220, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        String tipo = (String) jComboBox.getSelectedItem();

        DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
        String data = fmt.format(jDateChooser1.getDate());
        DespesaGanho dp = new DespesaGanho();
        DespesaGanhoDAO dpdao = new DespesaGanhoDAO();

        dp.setTipo(tipo);
        dp.setValor(Double.parseDouble(tfValor.getText()));
        dp.setDescricao(tfDescrição.getText());
        dp.setData(data);

        dpdao.create(dp);
        readFluxo();

    }//GEN-LAST:event_btnInserirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox jComboBox;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFluxo;
    private javax.swing.JTextField tfDescrição;
    private javax.swing.JTextField tfValor;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
